import adminRouter from "./admin";
import akifIntelligenceRouter from "./akifIntelligence";
import akifOperationsRouter from "./akifOperations";
import akifStoreRouter from "./akifStore";
import akifHermesRouter from "./akifHermes";
import akifOfficialSourcesRouter from "./akifOfficialSources";
import akifImpexqRouter from "./akifImpexq";
import authRouter from "./auth";
import buyerPoolsRouter from "./buyerPools";
import commissionRouter from "./commissions";
import companyRouter from "./company";
import { Router, type IRouter } from "express";
import databaseRouter from "./database";
import dashboardRouter from "./dashboard";
import dealRouter from "./deals";
import documentRouter from "./documents";
import healthRouter from "./health";
import marketplaceRouter from "./marketplace";
import notificationRouter from "./notifications";
import privacyRouter from "./privacy";
import profileRouter from "./profile";
import referralRouter from "./referrals";
import submissionRouter from "./submissions";
import whatsappBuyerIntakeRouter from "./whatsappBuyerIntake";
import whatsappWebhookRouter from "./whatsappWebhook";

const router: IRouter = Router();

router.use(healthRouter);
router.use(databaseRouter);
router.use(dashboardRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(privacyRouter);
router.use(marketplaceRouter);
router.use(submissionRouter);
router.use(referralRouter);
router.use(commissionRouter);
router.use(notificationRouter);
router.use(documentRouter);
router.use(dealRouter);
router.use(buyerPoolsRouter);
router.use(companyRouter);
router.use(adminRouter);
router.use(akifIntelligenceRouter);
router.use(akifOperationsRouter);
router.use(akifStoreRouter);
router.use(akifHermesRouter);
router.use(akifOfficialSourcesRouter);
router.use(akifImpexqRouter);
router.use(whatsappBuyerIntakeRouter);
router.use(whatsappWebhookRouter);

export default router;
